### ISSUE TITLE
SEND/RECV deadlock...

### ISSUE THREAD

**Issue by nklein** [zkat/chanl#11] opened 2015-11-06 17:29 UTC
Someone posted a program to [Reddit](https://www.reddit.com/r/lisp/comments/3rlyxu/is_it_chanl_problems_please_help_this_test/cwqtzi3) that deadlocks when using `CHANL`.  I spent a bit of time looking into it.  I think I see why it deadlocks.

The deadlock looks like a `CHANL` bug to me.  Specifically, the use of `RECV-GRABBED-VALUE-P` can get into a situation where multiple `SEND` calls are blocking waiting for it to become true.  If, while multiple `SEND` calls are blocking waiting for it to become true, multiple readers sneak in and all of them set it to true, then only one of the `SEND` calls will complete.

It seems to me this could happen even without the extra `SEMAPHORE` in the sample code.  I think the semaphore just keeps the send threads from happening almost entirely serially.

```
(ql:quickload :chanl)  
(ql:quickload :bordeaux-threads)  
#+sbcl (ql:quickload :sb-concurrency)  

(defun test-chanl (n)  
  (loop for i from 0 below n do  
       (format t "~&Test: ~a~%" i)  
       (let* ((size 1024)  
              (test-repeat 4)  
              (chanl (make-instance 'chanl:unbounded-channel))  
              (semaphore #+sbcl (sb-thread:make-semaphore)  
                         #+ccl (make-semaphore)))  
         (loop repeat test-repeat do  
              (bt:make-thread  
               (lambda ()
                 #+sbcl (sb-thread:wait-on-semaphore semaphore)  
                 #+ccl (wait-on-semaphore semaphore)
                 (loop repeat size  
                    do (chanl:send chanl 1)))))  
         (loop repeat test-repeat  
            do #+sbcl (sb-thread:signal-semaphore semaphore)  
              #+ccl (signal-semaphore semaphore))  
         (loop repeat (* size test-repeat)  
            for i from 0  
            do (chanl:recv chanl))))  
  (format t "~&done.~%"))
```

I'll see if I can create some simpler code to trigger it.  It looks like the fix would be switching to a counter (or semaphore) rather than a boolean for the number of senders waiting.

**Comment by nklein** [comment] 2015-11-06 17:44
Here is a case that reproduces it very reliably when thread-count is greater than 1.

    (defun test-chanl (thread-count)
      (let ((senders 0)
            (receivers 0)
            (channel (make-instance 'chanl:unbounded-channel)))
        (macrolet ((with-counter ((place) &body body)
                     `(unwind-protect
                           (progn
                             (incf ,place)
                             ,@body)
                        (decf ,place))))
          (flet ((send-func ()
                   (with-counter (senders)
                     (chanl:send channel 'foo)))

                 (recv-func ()
                   (with-counter (receivers)
                     (chanl:recv channel))))

            (let ((threads (loop :for s :from 0 :below thread-count
                              :collect (bt:make-thread #'send-func
                                                       :name (format nil
                                                                     "SENDER-~D"
                                                                     s)))))

              ;; wait until all senders have started trying to send
              (loop :until (= senders thread-count))

              ;; do all the recvs
              (loop :repeat thread-count
                 :do (recv-func))

              ;; wait for all sends to finish
              (loop :for thread :in threads
                 :do (bt:join-thread thread)))))))

**Comment by nklein** [comment] 2015-11-06 18:21
This code isn't any shorter, but it does pretty reliably reproduce the issue for `thread-count` of 5 or 10.

    (ql:quickload :chanl)  
    (ql:quickload :bordeaux-threads)  

    (defun test-chanl (thread-count)
      (let ((lock (bt:make-lock "counter-lock"))
            (receivers 0)
            (senders 0)
            (channel (make-instance 'chanl:unbounded-channel))
            (start nil))
        (macrolet ((with-counter ((place) &body body)
                     `(unwind-protect
                           (progn
                             (bt:with-lock-held (lock)
                               (incf ,place))
                             ,@body)
                        (bt:with-lock-held (lock)
                          (decf ,place)))))
          (flet ((recv-func ()
                   (with-counter (receivers)
                     (chanl:recv channel)))

                 (send-func ()
                   (with-counter (senders)
                     (loop :until start :do (bt:thread-yield))
                     (loop :repeat repeat-count
                        :do (chanl:send channel :foo)))))

            (let ((threads (loop :for s :from 0 :below thread-count
                              :collect (bt:make-thread #'recv-func
                                                       :name (format nil
                                                                     "READER-~D"
                                                                     s))
                              :collect (bt:make-thread #'send-func
                                                       :name (format nil
                                                                     "SENDER-~D"
                                                                     s)))))

              ;; wait until all readers have started trying to read
              (loop :until (= receivers thread-count))

              ;; wait until all writers have started
              (loop :until (= senders thread-count))

              (format t "Starting SENDs.")
              (setf start t)

              ;; wait for all threads to finish
              (loop :for thread :in threads
                 :do (bt:join-thread thread)))))))

**Comment by fade** [comment] 2015-11-06 18:31
On 15-11-06 01:21 PM, Patrick Stein wrote:
>
> This code isn't any shorter, but it does pretty reliably reproduce the
> issue for |thread-count| of 5 or 10.
>
> |(ql:quickload :chanl) (ql:quickload :bordeaux-threads) (defun
> test-chanl (thread-count) (let ((lock (bt:make-lock "counter-lock"))
> (receivers 0) (senders 0) (channel (make-instance
> 'chanl:unbounded-channel)) (start nil)) (macrolet ((with-counter
> ((place) &body body) `(unwind-protect (progn (bt:with-lock-held (lock)
> (incf ,place)) ,@body) (bt:with-lock-held (lock) (decf ,place)))))
> (flet ((recv-func () (with-counter (receivers) (chanl:recv channel)))
> (send-func () (with-counter (senders) (loop :until start :do
> (bt:thread-yield)) (loop :repeat repeat-count :do (chanl:send channel
> :foo))))) (let ((threads (loop :for s :from 0 :below thread-count
> :collect (bt:make-thread #'recv-func :name (format nil "READER-~D" s))
> :collect (bt:make-thread #'send-func :name (format nil "SENDER-~D"
> s))))) ;; wait until all readers have started trying to read (loop
> :until (= receivers thread-count)) ;; wait until all writers have
> started (loop :until (= senders thread-count)) (format t "Starting
> SENDs.") (setf start t) ;; wait for all threads to finish (loop :for
> thread :in threads :do (bt:join-thread thread))))))) |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zkat/chanl/issues/11#issuecomment-154491785>.
>

There's a bug in your test function. You are looping for repeat-count
:repeats, which is an undefined variable.

B

**Comment by nklein** [comment] 2015-11-06 18:32
See the edit to my comment.  I had repeat-count in and then took it out but accidentally undid the last modification while trying to indent everything to paste in as Markdown.  There is no longer any repeat-count in the comment.

**Comment by adlai** [comment] 2019-03-30 14:04
> The deadlock looks like a CHANL bug to me. Specifically, the use of RECV-GRABBED-VALUE-P can get into a situation where multiple SEND calls are blocking waiting for it to become true. If, while multiple SEND calls are blocking waiting for it to become true, multiple readers sneak in and all of them set it to true, then only one of the SEND calls will complete.

This scenario should be invalidated for unbuffered channels by the fact that the first action in their methods is requesting the channel lock; since the bug occurs even for unbuffered channels, there must be another scenario (or the issue is due to a problem with the locking implementation).

**Comment by imnisen** [comment] 2019-10-15 03:17
The `send/recv` for unbuffered channel causes deadlock also. 
You can refer to comment:https://github.com/zkat/chanl/issues/13#issuecomment-541347280

**Comment by adlai** [comment] 2019-10-16 06:44
> You can refer to comment:#13 (comment)

Thank you for bringing that comment to my attention; I'd likely have not noticed your message otherwise, due to the issue duplication.

> The send/recv for unbuffered channel causes deadlock also.
Indeed, the _Omega-th Law_ states that unfound bugs outnumber unimplemented tests.

**Comment by adlai** [comment] 2020-07-10 16:22
This should be fixed by commit 758e11b although I am leaving the issue open until the fix is confirmed.

**Comment by adlai** [comment] 2020-10-09 01:03
Consideration of factors outside the immediately imported package have led to this issue's abandonment, without a confirmed fix.

**Comment by adlai** [comment] 2024-11-20 00:57
I wrote a better test case and did not push to github because I work alone.

**Closed by adlai** 2024-11-20 00:57 UTC
Labels: bug
